### ISSUE TITLE
a user found a bug about sudo rights

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/manjaro-cli-installer#2]
please look in this thread:
https://forum.manjaro.org/index.php?topic=31892.0

in this post, the user explains what goes wrong in the cli-installer:
https://forum.manjaro.org/index.php?topic=31892.msg263479#msg263479

**Comment by aadityabagga** [comment]
To fix this issue, wheel group could be removed from the default groups:
https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/shared/profile.conf.example#L55

Not an installer bug per se.
